name: Ubuntu SSH Web Terminal

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  web-terminal:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.5.2

    - name: Update APT
      run: sudo apt-get update

    - name: Start Web Terminal using Gotty + Ngrok
      run: |
        echo "LINUX_USER_PASSWORD=$LINUX_USER_PASSWORD"
        echo "NGROK_AUTH_TOKEN=$NGROK_AUTH_TOKEN"
        chmod +x linux-run.sh
        ./linux-run.sh
      env:
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Keep Workflow Running for Access
      run: sleep 6h
